# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timagic.ui'
#
# Created: Fri Dec 13 11:54:42 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 433)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.deviceListWidget = QtGui.QListWidget(self.centralwidget)
        self.deviceListWidget.setGeometry(QtCore.QRect(10, 60, 181, 201))
        self.deviceListWidget.setObjectName("deviceListWidget")
        self.btnRun = QtGui.QPushButton(self.centralwidget)
        self.btnRun.setGeometry(QtCore.QRect(200, 218, 341, 51))
        self.btnRun.setObjectName("btnRun")
        self.radioBtnAndroidDevices = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnAndroidDevices.setGeometry(QtCore.QRect(240, 60, 251, 18))
        self.radioBtnAndroidDevices.setChecked(False)
        self.radioBtnAndroidDevices.setObjectName("radioBtnAndroidDevices")
        self.radioBtnAPK = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnAPK.setGeometry(QtCore.QRect(240, 99, 211, 18))
        self.radioBtnAPK.setChecked(False)
        self.radioBtnAPK.setObjectName("radioBtnAPK")
        self.radioBtnIPA = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnIPA.setGeometry(QtCore.QRect(240, 140, 151, 18))
        self.radioBtnIPA.setChecked(False)
        self.radioBtnIPA.setObjectName("radioBtnIPA")
        self.labelHeadline = QtGui.QLabel(self.centralwidget)
        self.labelHeadline.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("HanziPenTC-W3")
        font.setPointSize(28)
        self.labelHeadline.setFont(font)
        self.labelHeadline.setObjectName("labelHeadline")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 25, 531, 20))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 42, 91, 16))
        self.label.setObjectName("label")
        self.radioBtnIOS6 = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnIOS6.setEnabled(False)
        self.radioBtnIOS6.setGeometry(QtCore.QRect(270, 170, 97, 18))
        self.radioBtnIOS6.setCheckable(True)
        self.radioBtnIOS6.setAutoExclusive(True)
        self.radioBtnIOS6.setObjectName("radioBtnIOS6")
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioBtnIOS6)
        self.radioBtnIOS7 = QtGui.QRadioButton(self.centralwidget)
        self.radioBtnIOS7.setEnabled(False)
        self.radioBtnIOS7.setGeometry(QtCore.QRect(360, 170, 97, 18))
        self.radioBtnIOS7.setChecked(True)
        self.radioBtnIOS7.setAutoExclusive(True)
        self.radioBtnIOS7.setObjectName("radioBtnIOS7")
        self.buttonGroup.addButton(self.radioBtnIOS7)
        self.btnReloadProjects = QtGui.QToolButton(self.centralwidget)
        self.btnReloadProjects.setGeometry(QtCore.QRect(139, 44, 51, 17))
        self.btnReloadProjects.setObjectName("btnReloadProjects")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(480, 60, 51, 16))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelDeviceCount = QtGui.QLabel(self.frame)
        self.labelDeviceCount.setGeometry(QtCore.QRect(20, 2, 31, 15))
        self.labelDeviceCount.setObjectName("labelDeviceCount")
        self.btnReloadDeviceCount = QtGui.QToolButton(self.centralwidget)
        self.btnReloadDeviceCount.setGeometry(QtCore.QRect(480, 44, 51, 17))
        self.btnReloadDeviceCount.setIconSize(QtCore.QSize(14, 14))
        self.btnReloadDeviceCount.setObjectName("btnReloadDeviceCount")
        self.consoleLogTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.consoleLogTextEdit.setGeometry(QtCore.QRect(10, 270, 531, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleLogTextEdit.sizePolicy().hasHeightForWidth())
        self.consoleLogTextEdit.setSizePolicy(sizePolicy)
        self.consoleLogTextEdit.setAcceptDrops(False)
        self.consoleLogTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.consoleLogTextEdit.setReadOnly(True)
        self.consoleLogTextEdit.setObjectName("consoleLogTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 22))
        self.menubar.setObjectName("menubar")
        self.menuAPK_IPA_Magic = QtGui.QMenu(self.menubar)
        self.menuAPK_IPA_Magic.setObjectName("menuAPK_IPA_Magic")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRun_current_Configuration = QtGui.QAction(MainWindow)
        self.actionRun_current_Configuration.setObjectName("actionRun_current_Configuration")
        self.menuAPK_IPA_Magic.addAction(self.actionRun_current_Configuration)
        self.menuAPK_IPA_Magic.addAction(self.actionAbout)
        self.menuAPK_IPA_Magic.addAction(self.actionClose)
        self.menubar.addAction(self.menuAPK_IPA_Magic.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.radioBtnIPA, QtCore.SIGNAL("toggled(bool)"), self.radioBtnIOS6.setEnabled)
        QtCore.QObject.connect(self.radioBtnIPA, QtCore.SIGNAL("toggled(bool)"), self.radioBtnIOS7.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TiMagic", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setText(QtGui.QApplication.translate("MainWindow", "RUN", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnAndroidDevices.setText(QtGui.QApplication.translate("MainWindow", "Install to connected Android Devices: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnAPK.setText(QtGui.QApplication.translate("MainWindow", "Create Google Play Store APK", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnIPA.setText(QtGui.QApplication.translate("MainWindow", "Create Ad-Hoc IPA", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHeadline.setText(QtGui.QApplication.translate("MainWindow", "TiMagic", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Select Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnIOS6.setText(QtGui.QApplication.translate("MainWindow", "iOS 6.1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnIOS7.setText(QtGui.QApplication.translate("MainWindow", "iOS 7.0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReloadProjects.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDeviceCount.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReloadDeviceCount.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAPK_IPA_Magic.setTitle(QtGui.QApplication.translate("MainWindow", "TiMagic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_current_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_current_Configuration.setToolTip(QtGui.QApplication.translate("MainWindow", "Run the currently active configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_current_Configuration.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))

